#!/bin/bash

echo ""
echo "-------------------------------------------------------------------"
echo " "
echo " This bash  script will stop Splunk services "
echo ""
echo " To shut down splunk "
echo " $ /opt/splunk/bin/./splunk stop "
echo " --------------------------------------------------------------------- "
echo ""
echo ""

read -n 1 -r -s -p $'Press enter to continue...\n'

/opt/splunk/bin/./splunk stop
